return {
    {
        -- 'nvim-lualine/lualine.nvim',
        -- dependencies = { 'nvim-tree/nvim-web-devicons' },
        -- config = function()
        --     require('lualine').setup({
        --         options = {
        --             theme = 'auto',
        --             component_separators = " ",
        --             section_separators = { left = "", right = "" },
        --         },
        --         sections = {
        --             lualine_c = {
        --                 {
        --                     'filename',
        --                     file_status = true,      -- Displays file status (readonly status, modified status)
        --                     newfile_status = false,  -- Display new file status (new file means no write after created)
        --                     path = 3,                -- 0: Just the filename
        --                     -- 1: Relative path
        --                     -- 2: Absolute path
        --                     -- 3: Absolute path, with tilde as the home directory
        --                     -- 4: Filename and parent dir, with tilde as the home directory
        --                     shorting_target = 40,    -- Shortens path to leave 40 spaces in the window
        --                     -- for other components. (terrible name, any suggestions?)
        --                     symbols = {
        --                         modified = '[+]',      -- Text to show when the file is modified.
        --                         readonly = '[-]',      -- Text to show when the file is non-modifiable or readonly.
        --                         unnamed = '[No Name]', -- Text to show for unnamed buffers.
        --                         newfile = '[New]',     -- Text to show for newly created file before first write
        --                     }
        --                 }
        --             },
        --             lualine_x = {
        --                 {
        --                     'copilot',
        --                     symbols = {
        --                         status = {
        --                             icons = {
        --                                 enabled = " ",
        --                                 sleep = " ",   -- auto-trigger disabled
        --                                 disabled = " ",
        --                                 warning = " ",
        --                                 unknown = " "
        --                             },
        --                             hl = {
        --                                 -- use colors from gruvbox
        --                                 -- enabled = "#8F3F71",
        --                                 -- sleep = "#8F3F71",
        --                                 -- disabled = "#8F3F71",
        --                                 -- warning = "#8F3F71",
        --                                 -- unknown = "#8F3F71"
        --                             }
        --                         },
        --                         spinners = require("copilot-lualine.spinners").dots,
        --                         spinner_color = "#6272A4"
        --                     },
        --                     show_colors = true,
        --                     show_loading = true
        --                 },
        --                 'filesize',
        --                 'filetype'
        --             },
        --         }
        --     })
        --
        -- end
    },
}
