# unbind-key C-b # unbind default prefix
set -g prefix 'C-b' # set prefix to 'ctrl + a'
bind-key 'C-b' send-prefix # send prefix

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows
setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed
set -g mouse on
set-option -g status-position bottom
set-option -g default-shell $SHELL

set -g visual-activity off

bind 'h' split-window
bind 'v' split-window -h

set -g status-left " "
set -g status-right-length 60
set -g status-right " #h:#S  %b %d %H:%M "


setw -g mode-keys vi

# add command to reload tmux configuration
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
