local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>sf', builtin.find_files, {})
vim.keymap.set('n', '<leader>sgf', builtin.git_files, {})
vim.keymap.set('n', '<leader>sw', builtin.live_grep, {})
vim.keymap.set("n", "<leader>sq", "<cmd>Telescope quickfix<cr>")
vim.keymap.set('n', '<leader>sh', builtin.help_tags, {})
vim.keymap.set('n', '<leader>sk', builtin.keymaps, {})
vim.keymap.set("n", "<leader>std", "<cmd>TodoTelescope keywords=TODO,FIX<cr>")
