format = """
[█](#63F2F1)\
$username\
[](bg:#ABF8F7 fg:#63F2F1)\
$git_branch\
$git_status\
[](fg:#ABF8F7 bg:#7676FF)\
$c\
$golang\
$nodejs\
$python\
$rust\
$zig\
[](fg:#7676FF bg:#D4BFFF)\
$kubernetes\
[ ](fg:#D4BFFF )\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#63F2F1 fg:#2D2B40"
style_root = "bg:#63F2F1 fg:#2D2B40"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
style = "bg:#D4BFFF fg:#2D2B40"
format = '[ $symbol$context ]($style)'
disabled = false

[elixir]
symbol = " "
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#ABF8F7 fg:#2D2B40"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ABF8F7 fg:#2D2B40"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "󰆥 "
style = "bg:#7676FF"
pyenv_version_name = true
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'
# format = '[ ${symbol} (${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#7676FF"
format = '[ $symbol ($version) ]($style)'

[zig]
style = "bg:#7676FF"
format = '[ $symbol($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
