[character]
success_symbol = '[\$](bold green)'

[ruby]
disabled = true

[kubernetes]
format = '[⛵ $context \($namespace\)](bold blue) '
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'arn:.*/(?P<var_cluster>[\w-]+)' = 'eks-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[terraform]
format = '[tf $workspace]($style) '

[golang]
symbol = ' '
format = '[$symbol($version )]($style)'

[env_var.AWS_OKTA_PROFILE]
default = ''
format = '[$env_value]($style) '

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = 'aws '

[container]
format = '[$symbol \[$name\]]($style) '

# [git_branch]
# truncation_length = 25
# truncation_symbol = '*'
