format = """
[█](#63F2F1)\
$username\
[](bg:#ABF8F7 fg:#63F2F1)\
$git_branch\
$git_status\
[](fg:#ABF8F7 bg:#F48FB1)\
$kubernetes\
[ ](fg:#F48FB1 )\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#63F2F1 fg:#2D2B40 bold"
style_root = "bg:#63F2F1 fg:#2D2B40 bold"
format = '[$user ]($style)'
disabled = false

[directory]
disabled = true

[c]
symbol = " "
style = "bg:#F02E6E fg:#2D2B40"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
style = "bg:#F48FB1 fg:#2D2B40"
format = '[ $symbol$context ]($style)'
disabled = false

[git_branch]
symbol = ""
style = "bg:#ABF8F7 fg:#2D2B40"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ABF8F7 fg:#2D2B40"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#F02E6E fg:#2D2B40"
format = '[ $symbol($version) ]($style)'

[gradle]
style = "bg:#F02E6E fg:#2D2B40"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#F02E6E fg:#2D2B40"
format = '[ $symbol($version) ]($style)'

[python]
symbol = "󰆥 "
style = "bg:#F02E6E fg:#2D2B40"
pyenv_version_name = true
format = '[ $symbol($version) (\($virtualenv\)) ]($style)'
# format = '[ ${symbol} (${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#F02E6E fg:#2D2B40"
format = '[ $symbol($version) ]($style)'

[zig]
style = "bg:#F02E6E"
format = '[ $symbol($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
