format = '''
(bold purple) $directory$kubernetes$aws$git_branch$git_state$git_status$cmd_duration$python$character'''

[directory]
truncate_to_repo = false

[kubernetes]
format = '[󱃾 $context \($namespace\)](bold blue) '
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'arn:.*/(?P<var_cluster>[\w-]+)' = 'eks:$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[aws]
format = '[$symbol($profile \($region\))]($style) '
symbol = ' '
[aws.region_aliases]
ap-south-1 = 'aps1'
ap-south-2 = 'aps2'

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vimcmd_symbol = "[](green)"

[container]
disabled = true

[docker_context]
disabled = true

[ruby]
disabled = true

[nodejs]
disabled = true
