[character]
success_symbol = '[\$](bold green)'

[ruby]
disabled = true

[nodejs]
disabled = true

[kubernetes]
format = '[⛵ $context/$namespace](bold blue) '
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'arn:.*/(?P<var_cluster>[\w-]+)' = 'eks-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[golang]
disabled = true

# [env_var.AWS_OKTA_PROFILE]
# default = ''
# format = '[$env_value]($style) '

[aws]
format = '[$symbol($profile/$region)]($style) '
symbol = ' '
[aws.region_aliases]
ap-south-1 = 'mum'
ap-south-2 = 'hyd'

[container]
disabled = true
format = '[$symbol \[$name\]]($style) '

[docker_context]
disabled = true

# [git_branch]
# truncation_length = 25
# truncation_symbol = '*'
