import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/keybindings.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both" # (macos only)
decorations = "none"
dynamic_padding = true
opacity = 0.8
blur = true

[font]
# Installed by running 
# $ brew install font-caskaydia-cove-nerd-font -f
# Search for other fonts by running
# $ brew search font-
# Then copy the name of the font you want to install and run the 
# first commmand
# normal = { family = "Source Code Pro for Powerline" }
normal = { family = "Inconsolata-dz for Powerline" }
size = 15
# offset = { x = 0, y = 1 }
