import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/keybindings.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both" # (macos only)
decorations = "none"
dynamic_padding = true
opacity = 0.8
blur = true

[font]
# normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
# normal = {family = "FiraCode Nerd Font", style = "Regular"}
size = 14.5

[selection]
save_to_clipboard = true
