import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/keybindings.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both" # (macos only)
decorations = "none"
dynamic_padding = true
opacity = 0.8
blur = true

[font]
# Mono font's have smaller icons, so avoid them
normal = { family = "MesloLGM Nerd Font", style = "Regular" }
# normal = { family = "Hack Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15
